(dp1
S'output'
p2
S"<class 'serial.serialutil.SerialException'> device reports readiness to read but returned no data (device disconnected or multiple access on port?)"
p3
sS'layer'
p4
S'/home/bemobi/Downloads/web2py/applications/touch_pay_client/controllers/default.py'
p5
sS'code'
p6
S'<code object <module> at 0x7f44f8a24c30, file "/home/bemobi/Downloads/web2py/applications/touch_pay_client/controllers/default.py", line 10>'
p7
sS'snapshot'
p8
(dp9
sS'traceback'
p10
S'Traceback (most recent call last):\n  File "/home/bemobi/Downloads/web2py/gluon/restricted.py", line 219, in restricted\n    exec(ccode, environment)\n  File "/home/bemobi/Downloads/web2py/applications/touch_pay_client/controllers/default.py", line 93, in <module>\n  File "/home/bemobi/Downloads/web2py/gluon/globals.py", line 409, in <lambda>\n    self._caller = lambda f: f()\n  File "/home/bemobi/Downloads/web2py/applications/touch_pay_client/controllers/default.py", line 26, in find_finger\n    line = ser.readline()\n  File "/usr/lib/python2.7/dist-packages/serial/serialposix.py", line 495, in read\n    raise SerialException(\'device reports readiness to read but returned no data (device disconnected or multiple access on port?)\')\nSerialException: device reports readiness to read but returned no data (device disconnected or multiple access on port?)\n'
p11
s.